### ISSUE TITLE
5个类别（增加Van和Truck）

### ISSUE THREAD

**Issue by Lan2Kailee** [ZrrSkywalker/MonoDETR#15]
2022-06-28 12:11:15,184   INFO  ###################  Training  ##################
2022-06-28 12:11:15,184   INFO  Batch Size: 16
2022-06-28 12:11:15,184   INFO  Learning Rate: 0.000200
epochs:   0%|                                                                                                                         | 0/195 [00:00<?, ?it/s]Traceback (most recent call last):                                                                                                    | 0/232 [00:00<?, ?it/s]
  File "tools/train_val.py", line 112, in <module>
    main()
  File "tools/train_val.py", line 99, in main
    trainer.train()
  File "/home/ps/dyj/MonoDETR/lib/helpers/trainer_helper.py", line 76, in train
    self.train_one_epoch(epoch)
  File "/home/ps/dyj/MonoDETR/lib/helpers/trainer_helper.py", line 121, in train_one_epoch
    for batch_idx, (inputs, calibs, targets, info) in enumerate(self.train_loader):
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ps/dyj/MonoDETR/lib/datasets/kitti/kitti_dataset.py", line 294, in __getitem__
    mean_size = self.cls_mean_size[self.cls2id[objects[i].cls_type]]
IndexError: index 3 is out of bounds for axis 0 with size 3

您好，我增加两个类别后报以上这样的错误，请问下如何解决呢？

**Comment by MargeryLab** [comment]
> 2022-06-28 12:11:15,184 INFO ################### Training ################## 2022-06-28 12:11:15,184 INFO Batch Size: 16 2022-06-28 12:11:15,184 INFO Learning Rate: 0.000200 epochs: 0%| | 0/195 [00:00<?, ?it/s]Traceback (most recent call last): | 0/232 [00:00<?, ?it/s] File "tools/train_val.py", line 112, in main() File "tools/train_val.py", line 99, in main trainer.train() File "/home/ps/dyj/MonoDETR/lib/helpers/trainer_helper.py", line 76, in train self.train_one_epoch(epoch) File "/home/ps/dyj/MonoDETR/lib/helpers/trainer_helper.py", line 121, in train_one_epoch for batch_idx, (inputs, calibs, targets, info) in enumerate(self.train_loader): File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise raise self.exc_type(msg) IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ps/wlx/miniconda3/envs/pt19/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ps/dyj/MonoDETR/lib/datasets/kitti/kitti_dataset.py", line 294, in **getitem** mean_size = self.cls_mean_size[self.cls2id[objects[i].cls_type]] IndexError: index 3 is out of bounds for axis 0 with size 3
> 
> 您好，我增加两个类别后报以上这样的错误，请问下如何解决呢？

Have you solved this problem？

**Comment by zhang-lei-sudo** [comment]
我也有一样的问题，请问你解决了吗？
